spring.application.name=curso
# 1. Configura\u00e7\u00e3o da Conex\u00e3o com o PostgreSQL (Porta padr\u00e3o: 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/cursoPU?useSSL=false&serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=tatu

# 2. Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Configura\u00e7\u00f5es do Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# O 'update' faz o Spring criar ou atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Dialeto do PostgreSQL para o Hibernate gerar as queries corretas
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect