/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.infrastruture.util.StringUtil;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.stereotype.Component;

@Component
public class CursoListar extends javax.swing.JFrame {
    
private final CursoIController cursoController;
 
    public CursoListar(CursoIController cursoController) {
        this.cursoController = cursoController;
        initComponents(); // Deixe essa linha cinza em paz, o NetBeans cuida dela

        // Garanta que essas linhas de configuração da tabela continuem aqui:
        tblInformacao.getColumnModel().getColumn(0).setMinWidth(0);
        tblInformacao.getColumnModel().getColumn(0).setMaxWidth(0);
        tblInformacao.getColumnModel().getColumn(0).setWidth(0);

        findAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHomeScreen = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        lblPesquisa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInformacao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 84));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHomeScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/impressora.png"))); // NOI18N
        btnHomeScreen.setText("HomeScreen");
        btnHomeScreen.addActionListener(this::btnHomeScreenActionPerformed);
        jPanel1.add(btnHomeScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 130, -1));

        btnPesquisa.setBorderPainted(false);
        btnPesquisa.setContentAreaFilled(false);
        btnPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisa.setFocusPainted(false);
        btnPesquisa.addActionListener(this::btnPesquisaActionPerformed);
        jPanel1.add(btnPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 30, 20));

        txtPesquisa.setForeground(new java.awt.Color(102, 102, 102));
        txtPesquisa.setBorder(null);
        txtPesquisa.addActionListener(this::txtPesquisaActionPerformed);
        jPanel1.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 30, 230, 20));

        btnAdicionar.setBackground(new java.awt.Color(204, 222, 228));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/butao_mais.png"))); // NOI18N
        btnAdicionar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);
        jPanel1.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 120, -1));

        lblPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/barra_de_pesquisa.png"))); // NOI18N
        jPanel1.add(lblPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 290, 60));

        tblInformacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "PEIXE", "4", null, "Fazenda", "          [X]", "     [EDITAR]"},
                {null, "PÃO", "76", null, "Fazenda", "          [X]", "     [EDITAR]"},
                {null, "LEITE", "34", null, "Fazenda", "          [X]", "     [EDITAR]"},
                {null, null, null, null, null, "", null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "NOME", "QUANTIDADE", "DESCRIÇÃO", "FORNECEDOR", "REMOVER", "EDITAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInformacao.setFillsViewportHeight(true);
        tblInformacao.setSelectionForeground(new java.awt.Color(102, 102, 102));
        tblInformacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInformacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInformacao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 97, 670, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //adiciona um novo curso chamando o metodo save
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        save();
    }//GEN-LAST:event_btnAdicionarActionPerformed
    
    //metodo para salvar as informações
    private void save() {
        try {
            //coleta de dados
            String nome = JOptionPane.showInputDialog(this, "Nome do Curso:");
            String quantidade = JOptionPane.showInputDialog(this, "Quantidade:");
            String descricao = JOptionPane.showInputDialog(this, "Descrição do Curso:");
            String fornecedor = JOptionPane.showInputDialog(this, "Fornecedor:");

            //validação com StringUtil antes de criar o objeto
            if (StringUtil.isEmpty(nome)) {
                JOptionPane.showMessageDialog(this, "O nome do curso não pode estar vazio.");
                return;
            }

            //montagem do Objeto
            Curso novoCurso = new Curso();
            novoCurso.setNome(nome);
            novoCurso.setDescricao(descricao);
            novoCurso.setFornecedor(fornecedor);

            //validação de formato
            if (!StringUtil.isNumeric(quantidade)) {
                JOptionPane.showMessageDialog(this, "A quantidade deve ser um número válido.");
                return;
            }
            novoCurso.setQuantidade(Integer.parseInt(quantidade));

            //envia para o controller
            //controller passará para o service, que validará as regras de negócio
            cursoController.save(novoCurso); 

            JOptionPane.showMessageDialog(this, "Curso '" + nome + "' salvo com sucesso!");

            //atualiza a interface usando o novo nome padronizado
            findAll();

        } catch (Exception e) {
            //captura erros de validação vindos do Service ou erros de banco do DAO
            JOptionPane.showMessageDialog(this, "Erro ao processar: " + e.getMessage(), 
                                          "Erro de Sistema", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    //procura o curso pelo nome
    private void findByText() {
        // usa o stringutil para validar a entrada da view
        String termoBusca = txtPesquisa.getText().trim();
        
        if (StringUtil.isEmpty(termoBusca)) {
            findAll();
            return;
        }
        
        try {
            //view solicita a busca ao controller
            List<Curso> resultados = cursoController.findByText(termoBusca.trim());
        
            //se não encontrar nada
            if (resultados.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nenhum curso encontrado com: " + termoBusca);
            } else {
                //se encontrar apenas 1, mostra a janelinha com detalhes
                if (resultados.size() == 1) {
                    Curso c = resultados.get(0);
                    String info = "ID: " + c.getId() +
                                  "\nNome: " + c.getNome() +
                                  "\nQuantidade: " + c.getQuantidade() +
                                  "\nFornecedor: " + c.getFornecedor() +
                                  "\nDescrição: " + c.getDescricao();
                    JOptionPane.showMessageDialog(this, info, "Detalhes do Curso", JOptionPane.INFORMATION_MESSAGE);
                }
                
                updateTable(resultados);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro na busca: " + e.getMessage());
        } 
    }
    
    // Método auxiliar para não repetir código
    private void updateTable(List<Curso> lista) {
        DefaultTableModel modelo = (DefaultTableModel) tblInformacao.getModel();
        modelo.setRowCount(0);
        
        for (Curso c : lista) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getQuantidade(),
                c.getDescricao(),
                c.getFornecedor(),
                "[X]",
                "[EDITAR]"
            });
        }
    }
    
    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        findByText();
    }//GEN-LAST:event_btnPesquisaActionPerformed
    
    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        findByText();
    }//GEN-LAST:event_txtPesquisaActionPerformed

    //aciiona um evento ao clicar na tabela remover ou editar
    private void tblInformacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInformacaoMouseClicked
        int linha = tblInformacao.getSelectedRow();
        int coluna = tblInformacao.getSelectedColumn();

        //pegamos o ID da coluna 0
        Long id = (Long) tblInformacao.getValueAt(linha, 0);

        //botão de remover
        if (coluna == 5) {
            String nome = tblInformacao.getValueAt(linha, 1).toString();

            int confirmacao = JOptionPane.showConfirmDialog(this, 
                    "Deseja realmente excluir o curso: " + nome + "?", 
                    "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);

            if (confirmacao == JOptionPane.YES_OPTION) {
                delete(id);
            }
        }

        //botão de editar
        if (coluna == 6) {
            //pega as informações atuais da linha
            String nome = tblInformacao.getValueAt(linha, 1).toString();
            String qtd  = tblInformacao.getValueAt(linha, 2).toString();
            String desc = tblInformacao.getValueAt(linha, 3).toString();
            String forn = tblInformacao.getValueAt(linha, 4).toString();

            editarCurso(id, nome, qtd, desc, forn);
        }
    }//GEN-LAST:event_tblInformacaoMouseClicked

    //mostra a página como ela estava originalmente
    private void btnHomeScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeScreenActionPerformed
        findAll();
    }//GEN-LAST:event_btnHomeScreenActionPerformed
    
    //editar as informções do curso
    private void editarCurso(Long id, String nomeAt, String qtdAt, String descAt, String fornAt) {
        //abre as janelas de input com os valores atuais
        String novoNome = JOptionPane.showInputDialog(this, "Nome do Curso:", nomeAt);
        String novaQtd  = JOptionPane.showInputDialog(this, "Quantidade:", qtdAt);
        String novaDesc = JOptionPane.showInputDialog(this, "Descrição:", descAt);
        String novoForn = JOptionPane.showInputDialog(this, "Fornecedor:", fornAt);

        //se o usuário não cancelou (novoNome != null)
        if (novoNome != null) {
            try {
                //validação visual rápida com o StringUtil
                if (StringUtil.isEmpty(novoNome) || !StringUtil.isNumeric(novaQtd)) {
                    JOptionPane.showMessageDialog(this, "Dados inválidos! Verifique o nome e a quantidade.");
                    return;
                }

                Curso cursoEditado = new Curso();
                cursoEditado.setId(id); 
                cursoEditado.setNome(novoNome);
                cursoEditado.setDescricao(novaDesc);
                cursoEditado.setFornecedor(novoForn);
                cursoEditado.setQuantidade(Integer.parseInt(novaQtd));

                //chama o controller que vai chamar o service e DAO
                cursoController.save(cursoEditado);

                JOptionPane.showMessageDialog(this, "Curso atualizado com sucesso!");
                //atualiza a tabela
                findAll(); 

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao editar: " + e.getMessage());
            }
        }
    }
    
    //aprensenta a opção do usuário deletar o curso
    private void delete(Long id) {
        try {
            //a view solicita a exclusão ao controller
            cursoController.delete(id);

            JOptionPane.showMessageDialog(this, "Curso removido com sucesso!");

            //atualiza a tabela para o curso sumir da tela
            findAll();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao remover: " + e.getMessage());
        }
    }
    
    //lista todos os cursos
    private void findAll(){
        try {
            //agora solicita os dados ao controller, que faz a ponte até o banco
            List<Curso> lista = cursoController.findAll();
            
            //pega o modelo da tabela e limpa as linhas atuais
            DefaultTableModel modelo = (DefaultTableModel) tblInformacao.getModel();
            modelo.setRowCount(0);
            
            //percorre a lista de cursos e adiciona cada um na tabela
            for (Curso c : lista) {
                modelo.addRow(new Object[]{
                    c.getId(),
                    c.getNome(),
                    c.getQuantidade(),
                    c.getDescricao(),
                    c.getFornecedor(),
                    "[X]",
                    "[EDITAR]"
                });
            }
            
            //ajusta a altura da linha
            tblInformacao.setRowHeight(30);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao listar cursos: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnHomeScreen;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JTable tblInformacao;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
